#!/usr/bin/env bash
# notify.sh — Email notifications via msmtp
# Part of computile-backup-agent

[[ -n "${_NOTIFY_SH_LOADED:-}" ]] && return 0
_NOTIFY_SH_LOADED=1

# ──────────────────────────────────────────────
# Email sending
# ──────────────────────────────────────────────
send_email() {
    local subject="$1"
    local body="$2"
    local to="${3:-${EMAIL_TO:-}}"

    if [[ "${EMAIL_ENABLED:-no}" != "yes" ]]; then
        log_debug "Email notifications disabled"
        return 0
    fi

    if [[ -z "$to" ]]; then
        log_warn "EMAIL_TO not configured, cannot send notification"
        return 1
    fi

    local from="${EMAIL_FROM:-backup@computile.be}"

    # Build the email
    local email_content
    email_content=$(cat <<EOF
From: ${from}
To: ${to}
Subject: ${subject}
Content-Type: text/plain; charset=UTF-8

${body}
EOF
)

    log_debug "Sending email to $to: $subject"

    # Send via msmtp
    if echo "$email_content" | msmtp --read-envelope-from "$to" 2>/dev/null; then
        log_info "Email notification sent to $to"
        return 0
    else
        log_error "Failed to send email notification to $to"
        return 1
    fi
}

# ──────────────────────────────────────────────
# Notification templates
# ──────────────────────────────────────────────
notify_failure() {
    local step="${1:-unknown}"
    local details="${2:-No details available}"

    local subject="[BACKUP FAILED] ${CLIENT_ID}/${HOST_ID} — ${step}"

    local body
    body=$(cat <<EOF
BACKUP FAILURE REPORT
=====================

Client:      ${CLIENT_ID:-unknown}
Host:        ${HOST_ID:-unknown}
Environment: ${ENVIRONMENT:-unknown}
Date:        $(date '+%Y-%m-%d %H:%M:%S %Z')
Duration:    $(get_elapsed 2>/dev/null || echo "N/A")
Failed step: ${step}

ERRORS:
$(get_error_summary 2>/dev/null || echo "No error details captured")

DETAILS:
${details}

WARNINGS:
$(get_warning_summary 2>/dev/null || echo "None")

---
Log file: ${LOG_FILE:-N/A}
Repository: ${RESTIC_REPOSITORY:-N/A}

This is an automated message from computile-backup-agent.
EOF
)

    send_email "$subject" "$body" || true
}

notify_success() {
    if [[ "${EMAIL_ON_SUCCESS:-no}" != "yes" ]]; then
        return 0
    fi

    local snapshot_info="${1:-}"
    local subject="[BACKUP OK] ${CLIENT_ID}/${HOST_ID}"

    local body
    body=$(cat <<EOF
BACKUP SUCCESS REPORT
=====================

Client:      ${CLIENT_ID:-unknown}
Host:        ${HOST_ID:-unknown}
Environment: ${ENVIRONMENT:-unknown}
Date:        $(date '+%Y-%m-%d %H:%M:%S %Z')
Duration:    $(get_elapsed 2>/dev/null || echo "N/A")

SNAPSHOT:
${snapshot_info:-No snapshot details available}

WARNINGS:
$(get_warning_summary 2>/dev/null || echo "None")

---
Repository: ${RESTIC_REPOSITORY:-N/A}

This is an automated message from computile-backup-agent.
EOF
)

    send_email "$subject" "$body" || true
}

# ──────────────────────────────────────────────
# msmtp configuration helper
# ──────────────────────────────────────────────
generate_msmtp_config() {
    local config_file="${1:-/etc/computile-backup/msmtprc}"

    if [[ -z "${SMTP_HOST:-}" ]]; then
        log_warn "SMTP_HOST not configured, cannot generate msmtp config"
        return 1
    fi

    local smtp_pass=""
    if [[ -n "${SMTP_PASS_FILE:-}" ]] && [[ -f "${SMTP_PASS_FILE}" ]]; then
        smtp_pass=$(read_secret_file "$SMTP_PASS_FILE")
    fi

    cat > "$config_file" <<EOF
# Generated by computile-backup-agent
account default
host ${SMTP_HOST}
port ${SMTP_PORT:-587}
auth on
user ${SMTP_USER:-${EMAIL_FROM:-backup@computile.be}}
password ${smtp_pass}
from ${EMAIL_FROM:-backup@computile.be}
tls on
tls_starttls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile /var/log/msmtp.log
EOF

    chmod 600 "$config_file"
    log_info "Generated msmtp config: $config_file"
}

# ──────────────────────────────────────────────
# Setup msmtp if needed
# ──────────────────────────────────────────────
setup_msmtp_if_needed() {
    if [[ "${EMAIL_ENABLED:-no}" != "yes" ]]; then
        return 0
    fi

    local msmtp_config="/etc/computile-backup/msmtprc"

    # If msmtp config doesn't exist and we have SMTP settings, generate it
    if [[ ! -f "$msmtp_config" ]] && [[ -n "${SMTP_HOST:-}" ]]; then
        log_info "Generating msmtp configuration"
        generate_msmtp_config "$msmtp_config"
    fi

    # Point msmtp to our config
    if [[ -f "$msmtp_config" ]]; then
        export MSMTP_CONF="$msmtp_config"
    fi
}
